---
title: 'Local Equilibrium Chemistry in R --- part II: Two Equilibrium Reactions'
subtitle: "Exercises Accompanying the Course Reaction Transport Modelling in the Hydrosphere"
author: "Karline Soetaert and Lubos Polerecky, Utrecht University"
date: "February 2021"
output:
  pdf_document:
    number_sections: false
  html_document: default
---

```{echo = FALSE, include = FALSE}
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Equilibrium chemistry II, two equilibrium reactions: modelling exercise}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
```

# Problem

In part I of the Reader "Local equilibrium chemistry in R", we have shown how to model situations where a fast reversible reaction involving *three* chemical species --- ammonium ($NH_4^+$), ammonia ($NH_3$) and protons ($H^+$) --- is coupled to a slow irreversible process that affects (adds or removes) one of the species ($NH_3$). We have seen that if we are only interested in modelling the dynamics due to the slow process, we can significantly simplify the model by reformulating it in terms of new state variables --- so-called "lump-sum species". For the fast equilibration reaction $NH_4^+ \leftrightarrow NH_3 + H^+$, these new lump-sum species were the total ammonia, $NH_x = NH_3 + NH_4^+$, and the total positive charge, $H_x = NH_4^+ + H^+$.

Here, we will expand this approach to a similar situation but involving *four* chemical species --- carbonic acid ($H_2CO_3$), bicarbonate ($HCO_3^-$), carbonate ($CO_3^{2-}$), and protons ($H^+$). Specifically, we will consider that two fast reversible reactions\footnote{In this analysis, we will neglect dissociation of water, $H_2O \leftrightarrow H^+ + OH^-$.}
$$Reaction~1: \quad H_2CO_3\leftrightarrow HCO_3^- + H^+$$
and
$$Reaction~2: \quad HCO_3^- \leftrightarrow CO_3^{2-} + H^+$$
are coupled to a slow process that specifically affects (adds or removes) $H_2CO_3$.\footnote{This process could be, for example, the addition of $H_2CO_3$ due to the exchange with atmospheric CO$_2$ or due to the mineralization of organic matter. Note that each of these processes is already a two-step process: the addition of CO$_2$ to water, which is a slow irreversible process, followed by a chemical reaction $CO_2 + H_2O \leftrightarrow H_2CO_3$, which is a fast reversible process. However, because the rate of the overall process is limited by the rate of the slow process, we can consider the net effect of these two processes to be a slow addition of $H_2CO_3$. Depending on the perspective, and given the reactions 1 and 2, one can also consider it as a slow addition of $HCO_3^- + H^+$ or $CO_3^{2-} + 2H^+$. However, here we will consider $H_2CO_3$ as the added species.} The overall approach will be very similar, although the mathematical treatment will be more challenging due to the greater number of species involved (4 instead of 3). Nevertheless, the outcome will be the same: if we are only interested in modelling the dynamics due to the slow process, we can significantly simplify the model by reformulating it in terms of "lump-sum" species. We will show that for the fast equilibration reactions 1 and 2, these new lump-sum species are the total dissolved inorganic carbon, $DIC = H_2CO_3  + HCO_3^- + CO_3^{2-}$, and the carbonate alkalinity, $ALK = HCO_3^- + 2\cdot CO_3^{2-} - H^+$. Ultimately, this Reader aims to explain how to model changes in pH due to the slow addition/removal of DIC to/from water.

# Approach

The aproach followed in this Reader is based on a set of tasks that you should be able to solve on your own if you have understood the material presented in part I of the Reader. It is challenging, but possible if you are motivated, persistent, and patient. If you feel you are stuck, you can of course look up the solutions provided at the end of this document. But we encourage you to try first on your own.


## Task 1: Mass balance equations of the carbonate system

Assume that the forward and backward reactions 1 and 2 are *elementary reactions*. Denote the corresponding rate constants as $k_{1f}$ (units of $s^{-1}$) and $k_{1b}$ (units of $(mol~L^{-1})^{-1}~s^{-1}$) for the reaction 1, and $k_{2f}$ and $k_{2b}$ (the same units) for the reaction 2. Additionally, assume that the species $H_2CO_3$ is added at a rate $R_C$ ($mol~L^{-1}~s^{-1}$).

* Formulate mass balance equations considering the three processes, reactions 1 and 2 and the process with rate $R_C$. 

You should arrive at 4 differential equations for the state variables $[H_2CO_3]$, $[HCO_3^-]$, $[CO_3^{2-}]$, and $[H^+]$. Be careful with the stoichiometric coeficients.

## Task 2: Equilibrium conditions

Assume that the rate of the slow process is zero ($R_C=0$). Using the mass balance equations formulated in Task 1, 

* derive relationships between the equilibrium concentrations of the state variables describing the carbonate system. Hint: consider that the time-derivatives of the state variables are zero when the system is in an equilibrium.

You should arrive at *two* equations that relate the equilibrium concentrations of [$H_2CO_3$], [$HCO_3^-$], [$CO_3^{2-}$], and [$H^+$]. To simplify the relationships, define the ratios between the forward and backward rate constants as the so-called dissociation constants: $K_1 = k_{1f}/k_{1b}$ and $K_2 = k_{2f}/k_{2b}$. For a temperature of 25 $^\circ$C, salinity 35 and pressure of 1 bar, their values are approximately $K_1 = 1.422\times10^{-6}~mol~L^{-1}$ and $K_2=1.082\times10^{-9}~mol~L^{-1}$. The values for these constants at other conditions can be calculated using R-packages *seacarb* (Gattuso et al., 2020) and *AquaEnv* (Hofmann et al., 2010).

## Task 3: Lump-sum species

* Show that if you define the lump-sum species as $DIC = H_2CO_3  + HCO_3^- + CO_3^{2-}$ and $ALK = HCO_3^- + 2\cdot CO_3^{2-} - H^+$, their time derivatives 
are only affected by the slow process but *not* by the reversible reactions 1 and 2. 

Note that these new state variables correspond to the *total concentration of dissolved inorganic carbon* (DIC) and the *excess concentration of negatively charged species* (ALK) in the system. 

## Task 4: From lump-sum species to original species

Assume that the system is in an equilibrium, and that the concentrations $[DIC]$, $[ALK]$ and $[H^+]$ are *known*. Note that $pH = -\log{[H^+]}$, where $[H^+]$ is expressed in mol/liter of solution. Using the equilibrium relationships found in Task 2, 

* derive expressions for $[H_2CO_3]$, $[HCO_3^-]$, and $[CO_3^{2-}]$ as a function of $[DIC]$ and $[H^+]$.
* find a relationship between $[ALK]$, $[DIC]$ and $[H^+]$ from which one of the three state variables can be calculated provided that the other two are known.

This will be somewhat laborious, but rather straight forward. 

## Task 5: Application to atmospheric CO2 exchange
Consider seawater with a pH of 8 and a DIC concentration of $2~mmol~L^{-1}$. Assume that dissolved $CO_2$ is added to the water at a rate $0.1~mmol~L^{-1}~d^{-1}$, and that this is a slow process in comparison to the equilibration reactions 1 and 2. Additionally, assume that the reactions 1, 2 and the slow process with the rate $R_C$ are the only processes in the system.

* Write a model to predict the dynamics of the carbonate species, alkalinity and pH due to this process. You can start with the R-markdown template model file *RTM_equilibrium.Rmd*.\footnote{You can obtain this file from Rstudio: File $\rightarrow$ new File $\rightarrow$ Rmarkdown $\rightarrow$ from template $\rightarrow$ RTM\_equilibrium. Save this file under a different name, do not forget to change the heading of this file.}

Implement the model for the temperature of 20 $^\circ$C, salinity of 35, and pressure of 1 bar. For these conditions, the dissociation constants $K_1$ and $K_2$ are given above. You can start with the R-markdown template model file *RTMtemplate0D.Rmd* to implement this model.\footnote{You can obtain this file from Rstudio: File $\rightarrow$ new File $\rightarrow$ Rmarkdown $\rightarrow$ from template $\rightarrow$ RTMtemplate0D. Save this file under a different name, do not forget to change the heading of this file.}

