---
title: "RTM course - Units"
author: "Lubos Polerecky and Karline Soetaert"
description: "exercises on working with units"
date: "March 2025"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(learnr)
```

## Tutorial

In this tutorial, we aim to show you some tips when calculating with quantities that have units.

You are advised to look through the following slides.

Slides available at <a href="Link_will_be_added" target="_blank">google-drive</a>

## Test yourself

```{r uM, echo=FALSE}
msg <- "If you made a mistake, revise the steps explained in the tutorial and try to follow them."

question("Convert the concentration of $20~nM$ to $mol~m^{-3}$. Note that there are multiple correct answers.", type = "learnr_checkbox",
 answer("$0.2 \\times 10^{-3} \\,mol\\, m^{-3}$"),
 answer("$2 \\times 10^{-6}\\,mol\\,m^{-3}$"),
 answer("$20 \\times 10^{-6}\\,mol\\,m^{-3}$", correct=TRUE),
 answer("$0.02 \\times 10^{-3}\\,mol\\,m^{-3}$", correct=TRUE),
 
 allow_retry = TRUE,
 incorrect=msg,
 correct=msg)
```

